<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/reset.css" type="text/css" media="all">
    <link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/layout.css" type="text/css" media="all">
    <link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/style.css" type="text/css" media="all">
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-1.6.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/cufon-yui.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/cufon-replace.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/Vegur_700.font.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/Vegur_400.font.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/Vegur_300.font.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery.easing.1.3.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/tms-0.3.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/tms_presets.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/backgroundPosition.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/atooltip.jquery.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/script.js"></script>


    
    
</head>
<?php
    $user_data = Zend_Auth::getInstance()->getStorage()->read();
?>
<body id="page1">
<div class="body1">
  <div class="main">
         <header>
      <div class="wrapper">
        <h1><a href="index.html" id="logo">Hope Center</a></h1>
        <nav>
          <ul id="top_nav">
            <li><a href="index.html"><img src="<?= $this->baseUrl() ?>/images/top_icon1.gif" alt=""></a></li>
            <li><a href="#"><img src="<?= $this->baseUrl() ?>/images/top_icon2.gif" alt=""></a></li>
            <li class="end"><a href="contact.html"><img src="<?= $this->baseUrl() ?>/images/top_icon3.gif" alt=""></a></li>
          </ul>
        </nav>
        <nav>
          <ul id="menu">
            <li id="menu_active"><a href="<?= $this->baseUrl() ?>/user/index">Home</a></li>
             <?php
                if (isset($user_data->id)){
             ?>
            <li><a href="<?= $this->baseUrl()?>/user/logout">Log out</a></li>
            <?php
                }
                else{
            ?>
            <li><a href="<?= $this->baseUrl()?>/user/signup">Sign Up</a></li>
            <li><a href="<?= $this->baseUrl()?>/user/login">Log In</a></li>
                            
            <?php
                }
            ?>
           
          </ul>
        </nav>
      </div>
      
    </header>
<?php echo $this->layout()->content; ?>
  </div>
</div>    
</body>

